### ISSUE TITLE
小游戏不错，有相应的api吗，比如移动、攻击

### ISSUE THREAD

**Issue by liub1934** [shinima/battle-city#15]
毕竟手机上操作不了。

**Comment by shinima** [comment]
暂时还没有，一开始开发的时候只考虑了 PC 。要在手机进行操作的话，还想要后续开发进行适配。不过目前阶段我上班比较忙，暂时不会开发了。

**Comment by gaelthas** [comment]
手机上可以下模拟器玩，几MB的模拟器，游戏更小
