### ISSUE TITLE
已知问题

### ISSUE THREAD

**Issue by shinima** [shinima/battle-city#2]
下面的问题算是已经解决，但有可能仍会出现：

- [x] 游戏偶尔会奔溃，截图见下方
- [x] 有的时候关卡会提前结束
- [x] 击毁所有的 AI 坦克之后没有自动进入下一关  fixed in 972f8b5ec7c08b420a3f2543dc30d7278724730e

---
已完成：

- [x] 两架坦克贴在一起的时候，其中一架进行转弯可能会和另一架坦克粘在一起 ( f6855e906ab9163c2adbc45491a79f8cc92bf188 8bff100791ddb7ab055092140ddf393728b8d0d3)
- [x] 有的时候无法显示部分贴图（例如 AI 坦克爆炸效果）
- [x] 因为老鹰被击毁而导致游戏结束时 场上坦克消失过快
- [x] 部分 PowerUp （例如 Shovel）的效果会留到下一个关卡
- [x] 编辑器：并不是每次goback 时都需要提醒「未保存的修改将丢失」
- [x] 游戏结束的时候 powerup、flicker、爆炸效果没有被正确清理

------
一些已经完成的功能可以在 #1 中查看

**Comment by shinima** [comment]
游戏偶尔会奔溃。
![image](https://user-images.githubusercontent.com/5550931/38676553-f4d629d2-3e8d-11e8-87ca-9f590410d9aa.png)

**Comment by PengbinLee** [comment]
- [X] 击毁所有的 AI 坦克之后没有自动进入下一关
这条还是会出现

**Comment by shinima** [comment]
@PengbinLee 好的，多谢反馈。看来关卡切换的时候问题还是比较多……
