### ISSUE TITLE
bug report：切换关卡之后 AI 玩家的控制器有时会找不到 AI 玩家

### ISSUE THREAD

**Issue by medmin** [shinima/battle-city#6]
我玩了4个关卡
除了第一关到第二关正常

第二关到第三关
第三关到 第四关
都是进入到新关之后，如果按任何一个键，都会出现卡死，就是地图上没有任何一个坦克，包括我自己的。
只好 重新刷新一下浏览器，就又出来了。

甚至不按任何键也可以出现这个问题。

**Comment by shinima** [comment]
好的，多谢反馈。我排查一下原因。

**Comment by shinima** [comment]
应该在 688d707 中修复了，我本地已经无法重现了
