### ISSUE TITLE
火狐浏览器不显示素材

### ISSUE THREAD

**Issue by BboyAwey** [shinima/battle-city#9]
firefox 59.0.2 (64 位)
不显示素材

![default](https://user-images.githubusercontent.com/15099804/38847051-343f2d88-4232-11e8-8a41-a4bcfe5a60dc.png)

**Comment by shinima** [comment]
多谢反馈，后续阶段我会修复的。

**Comment by shinima** [comment]
在 24b661a9d8366f578e87a26872fc561c8f24ad36 中已修复。目前 master 分支代码在 firefox62 中能够正常显示素材。
